### ISSUE TITLE
CUDA out of memory when train epoch after val

### ISSUE THREAD

**Issue by 1211186431** [Skype-line/X-Avatar#4]
Hello, I have successfully run the demo, and the results are good. But I encountered an issue while training on the 3090, and I hope you can help me resolve it.
I have modified the values of `datamodule.dataloader.batch_size` and `datamodule.dataloader.batch_size`, and I am able to successfully train for one epoch. But when it comes to the `check_val_every_n_epoch` epoch, it requires GPU memory to increase from 3GB to 22GB or even higher, which prevents me from saving the model and continuing the training.

**Comment by MohamedHussein736** [comment]
Hi, 
I solved this issue by reducing the output resolution by modifying opt.demo.resolution in the demo.py.  By default it is 512, try to reduce it.

**Comment by Skype-line** [comment]
You can reduce the “res_up” parameter [here](https://github.com/Skype-line/X-Avatar/blob/abf98296efac3e899f0e6450b76161adea755305/code/lib/xavatar_basic_model.py#L254).

**Comment by 1211186431** [comment]
Thank you, now I can start training. I found that the model trained with smpl requires more GPU memory than the one trained with smplx during testing. Is there any way to reduce the GPU memory usage when running` test.py`?
Apart from that, in `demo.py`, only the smplx model can be bound to actions. If you could provide a demo for binding actions to the smpl model, I would greatly appreciate it.

**Comment by Skype-line** [comment]
1. May I ask how long you have trained the model with SMPL before testing? I think the problem is our SMPL-X version is using the pretrained template model which already has a roughly human shape while the SMPL version is trained from scratch. If SMPL version is not fully trained, then the isosurface extraction will query more points so as to use more GPU memory. If the model is trained enough, the SMPL should not use more GPU memory during the testing. Of course, you can try to reduce the [batch_points](https://github.com/Skype-line/X-Avatar/blob/abf98296efac3e899f0e6450b76161adea755305/code/lib/xavatar_basic_model.py#L359) or [res_up](https://github.com/Skype-line/X-Avatar/blob/abf98296efac3e899f0e6450b76161adea755305/code/lib/xavatar_basic_model.py#L328).
2. The reason why we don't provide the SMPL version of `demo.py` is that we don't have the SMPL actions for the demo sequence. But you can either convert from SMPL-X to SMPL with the [official model transfer code](https://github.com/vchoutas/smplx/tree/main/transfer_model) or directly use [PyMAF](https://hongwenzhang.github.io/pymaf/) to obtain the SMPL parameters. And then you can easily modify the `demo.py` to make it run with SMPL parameters by taking a reference to `test.py`.

**Comment by 1211186431** [comment]
Thank you for your reply. I know how to solve the problems I encountered during training and testing.

**Comment by AryamanSharma17** [comment]
Hello @1211186431 , I am facing the same issue despite reducing batch_size=1 and points_per_frame = 30. Can you let me know how did you complete the training and the validation

**Comment by 1211186431** [comment]
> Hello @1211186431 , I am facing the same issue despite reducing batch_size=1 and points_per_frame = 30. Can you let me know how did you complete the training and the validation

Hope my experience can be useful to you. First of all, I want to ask which GPU you use for training, I use 3090 for training and testing. I suggest that you do not set `points_per_frame` too small, it is recommended to set it to 6000 and the same as the initial value if you use scan as input. If the `points_per_frame` is too small, the training effect may be much worse, resulting in more mesh points generated later and consuming more video memory. In addition, you can comment out the `plot` in val, which will also reduce the memory consumption of val.

**Comment by felixshing** [comment]
@1211186431 Hey, sorry to bother you again. May I ask have you successfully trained X-avatar on your dataset? I tried to do that but somehow the inference results are even not a human body but like the follwing one...
![xavatar_outputs00](https://github.com/Skype-line/X-Avatar/assets/61814345/3aa7acf4-5751-4ddf-be36-d6616ba72342)

**Comment by 1211186431** [comment]
First, regarding the issue with `res_up` I think you are correct. It is used to set the resolution of the output mesh. `res_up=4` will render a clearer mesh compared to `res_up=3` but it will also consume more GPU memory. As for how to set it, I believe it is a matter of personal preference since the visualization results during validation should not affect the network training.

Next, concerning training on your own dataset, I'm sorry to say that I haven't done that yet. However, I am interested in your results. Could you please let me know what format your own dataset is in? Perhaps I can analyze the reasons behind your results based on that.

**Comment by felixshing** [comment]
@1211186431 Thanks! I would love to share my data with you. Would you mind sending me your email address or wechat (if you have) to my email: rcheng4@gmu.edu? My dataset contains some private information and thus I am not willing to post it online.

Regarding the error, I have located the reason. After debugging, I found that the issue might stem from the part type prediction of each point. All points are being predicted as 'body', resulting in the omission of other parts like the face, hands, etc. Specifically, this code lies in "if self.opt.category_sample" of XHumans_rgbd.py. But I don't know why my dataset generates this issue and I am still debugging it.
